---
spring:
#  data:
#    elasticsearch:
#      cluster-nodes: localhost:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log #elasticsearch日志存储目录
#          data: ./elasticsearch/data #elasticsearch数据存储目录
#        transport:
#          tcp:
#            connect_timeout: 120s
#      cluster-name: elasticsearch

  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/blog
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true

  security:
    user:
      name: admin
      password: admin

  thymeleaf:
    cache: false
    mode: HTML5

file:
  server:
    url: http://localhost:8081/upload